### ISSUE TITLE
Add margin to options page

### ISSUE THREAD

**Issue by fapdash** [EMPRI-DEVOPS/empri-browser-extension#10]
Firefox: 
![screenshot_120](https://user-images.githubusercontent.com/459631/112500488-b82da580-8d88-11eb-9b53-7156988c4170.png)

**Comment by cburkert** [comment]
@fapdash Please check if the margins are okay with your dark mode, then you can close this.

**Comment by fapdash** [comment]
Looks okay, thank you.
