### ISSUE TITLE
Opera: options page not fully readable in dark mode

### ISSUE THREAD

**Issue by fapdash** [EMPRI-DEVOPS/empri-browser-extension#13]
![screenshot_122](https://user-images.githubusercontent.com/459631/112511499-c1237480-8d92-11eb-9915-a05019273a77.png)

**Comment by cburkert** [comment]
Is this a normal Opera theme @fapdash ? We never set any foreground ore background styles for our options so they "should" be inherited fine... Don't understand...

**Comment by fapdash** [comment]
### Opera
![screenshot_123](https://user-images.githubusercontent.com/459631/112681360-e4bbed00-8e6e-11eb-80a1-e1f9a0329b48.png)

### Firefox
![screenshot_124](https://user-images.githubusercontent.com/459631/112681357-e38ac000-8e6e-11eb-9caf-d4739b976e7d.png)

**Comment by fapdash** [comment]
Pretty sure the white area in Firefox is actually a Firefox bug. Our styling only applies to the space we actually fill out and they don't apply their default dark mode styling to the unused area.
