### ISSUE TITLE
Use fuzzy dates like "This year" on reduced precisions

### ISSUE THREAD

**Issue by mquintus** [EMPRI-DEVOPS/empri-browser-extension#19]
If precision is set to "per year", the empri-browser-extension sets all dates to e.g. the January 1st of the respective year and let github render it. This is sub-optimal.

Imagine a commit on Dec 31 2020.
Expected Behaviour:
```Last Year```
Actual Behaviour:
```16 Month ago```

Imagine a commit on Apr 18 2021.
Expected Behaviour:
```This Year```
Actual Behaviour:
```4 Month ago```

Imagine a release on 2021-04-16 14:41:04.
Expected Behaviour:
```github-actions released this this year```
Actual Behaviour:
``` github-actions released this on 1 Jan 2021```

![jan1st2021](https://user-images.githubusercontent.com/515945/115209932-5ef23100-a0fe-11eb-81b0-a17be822a577.png)

**Comment by cburkert** [comment]
Great feedback,  thanks!
Currently, GitHub's Timestamp rendering framework has no notion of fuzzy timestamps. This would be a great addition. I'll have a look how we could patch that in.

**Comment by cburkert** [comment]
Introduced with #25
