### ISSUE TITLE
Check lowering Firefox version requirement to 78

### ISSUE THREAD

**Issue by cburkert** [EMPRI-DEVOPS/empri-browser-extension#20]
Firefox version 78 is probably still widely used. It is currently  the version in Debian testing.
We should check if we can serve this version as well.

Current hinderance:
```
ANDROID_INCOMPATIBLE_API   browserAction.setIcon is not supported in   This API is not implemented by the given minimum Firefox for Android version   scripts/background.js   9      5     
                           Firefox for Android version 78.0                                                                                                                                
ANDROID_INCOMPATIBLE_API   browserAction.setIcon is not supported in   This API is not implemented by the given minimum Firefox for Android version   scripts/popup.js        30     9     
                           Firefox for Android version 78.0
```

**Comment by fapdash** [comment]
We can remove that requirement. Firefox for Android in the latest version only supports a few selected add-ons anyways, as far as I can tell. FF78 is the ESR (extended support release, basically LTS) on the desktop right now.

**Comment by fapdash** [comment]
The extension store might add the restriction anyways, but we'll see.
Right now we don't upload the study version to the store.
The api call in question is btw ```browser.browserAction.setIcon```.
