### ISSUE TITLE
Remove localhost host permission for production build

### ISSUE THREAD

**Issue by cburkert** [EMPRI-DEVOPS/empri-browser-extension#21]
Localhost permission is only used for development builds and should not be in the production version.

**Comment by fapdash** [comment]
I tried a few suggestions that I found on stackoverflow and in the [webextension-toolbox repo](https://github.com/webextension-toolbox/webextension-toolbox/issues/158) but to me it looks like the way to go right now is to generate the manifest.json in an extra build step before triggering the webextension-toolbox build.
