### ISSUE TITLE
"Comparing changes" pages don't get redacted

### ISSUE THREAD

**Issue by fapdash** [EMPRI-DEVOPS/empri-browser-extension#30]
URL: https://github.com/vogellacompany/empri-browser-extension/compare/main...EMPRI-DEVOPS:view-count

![screenshot_147](https://user-images.githubusercontent.com/459631/118719580-f09dad00-b828-11eb-8d4b-9003ed76ac52.png)

**Comment by cburkert** [comment]
This seems to be because the Timeline Item selector is too specific (no `.f5` here):
https://github.com/EMPRI-DEVOPS/empri-browser-extension/blob/33d921ca96a0b955aa57eedf7f07a6c2b4853ddc/app/scripts/redact.js#L367
