### ISSUE TITLE
Transition from issues overview to milestone doesn't trigger redaction

### ISSUE THREAD

**Issue by fapdash** [EMPRI-DEVOPS/empri-browser-extension#31]
URL: https://github.com/microsoft/iqsharp/issues?q=is%3Aopen+is%3Aissue
Verified in Firefox and Opera

https://user-images.githubusercontent.com/459631/118721177-d369de00-b82a-11eb-9624-5fea5682f962.mp4

**Comment by cburkert** [comment]
Easier reproduction: go from milestone list to milestone detail view.
Refresh hook seems to be triggered.

**Comment by cburkert** [comment]
The problem is that at the time the refresh hook is triggered, the `relative-date` elements as well as the whole issue data is not loaded yet.
Any suggestions @fapdash ?

**Comment by fapdash** [comment]
@cburkert I think https://github.com/EMPRI-DEVOPS/empri-browser-extension/commit/d644b6f767e2dc0093110b58d4c18d8a88bec211 fixes this issue, closing. Please reopen if the problem persists for you.

**Comment by cburkert** [comment]
Looks good for me as well 👍
