### ISSUE TITLE
Timestamps on Milestone pages don't get redacted

### ISSUE THREAD

**Issue by fapdash** [EMPRI-DEVOPS/empri-browser-extension#34]
URL: https://github.com/microsoft/vscode/milestones

The problem for us is that those aren't `<time-ago>` or `<relative-time>` tags but just spans.
I couldn't find an example with a due date so far but I assume that this will also just be in a span.

![screenshot_151](https://user-images.githubusercontent.com/459631/119172234-f9c78d80-ba65-11eb-9e35-6512591051f8.png)

![screenshot_152](https://user-images.githubusercontent.com/459631/119172231-f92ef700-ba65-11eb-9337-290647b788eb.png)

**Comment by cburkert** [comment]
Good catch. However, I think we shouldn't redact due dates because they are not timestamps of user interaction – so there is no privacy concern here.
