### ISSUE TITLE
Changing to /repo/commits/branch without full page reload breaks redaction

### ISSUE THREAD

**Issue by fapdash** [EMPRI-DEVOPS/empri-browser-extension#39]
https://user-images.githubusercontent.com/459631/125767410-8d8f09e1-2139-411a-b06d-5011c583361d.mp4

The video would have been more clear if I'd used the UI buttons for everything.
The actions that trigger the behavior are forward / backward in history, which uses pjax instead of a full page reload.
Verified in Firefox and Edge.

**Comment by cburkert** [comment]
Should be fixed with 0ec737567c843d689004153733dd8a90d27a117d:
@fapdash Please verify and close if fixed.

**Comment by fapdash** [comment]
Fixed, thank you!
