### ISSUE TITLE
Send report to backend once per day

### ISSUE THREAD

**Issue by fapdash** [EMPRI-DEVOPS/empri-browser-extension#4]
After each update to the study data we should check if it's been more than 24h since the last report to the backend.
If it's been more time then that we should send a message to the backend.

Proposed json format:

```json
{
  "participantIdentifier": "05137aaa-e88c-4d36-b12d-48286ade66aa",
  "entries": [
    {
      "url": "repository",
      "daysSinceOptIn" :12,
      "xpath": "DIV/DIV/RELATIVE-TIME",
      "mostSignificantUnit": "minute",
      "frequency": 1,
    },
    {
      "url": "repository_commit_list",
      "daysSinceOptIn": 14,
      "distanceStats": {
        "mean": 38177,
        "stddev": 53879
      },
      "xpath": "DIV/DIV/P/DIV/RELATIVE-TIME",
      "mostSignificantUnit": "hour",
      "frequency": 3,
    }              
  ]              
}
```

**Comment by cburkert** [comment]
@fapdash I'm changing the local study data accumulation for #3. Better don't touch that part yet.

**Comment by cburkert** [comment]
@fapdash I'm finishing the reporting except for the actual communication part.

**Comment by cburkert** [comment]
@fapdash The data format has changed:
- the day counter is now called `daysSinceOptIn` (should be covered already)
- entries _may_ now contain an optional `distanceStats` object (see above)

Can you please adopt the backend accordingly?
